"""
Constants and configuration values for the Decentralized Credential Platform
"""

# Platform Configuration
PLATFORM_NAME = "DecentralCredential"
PLATFORM_VERSION = "1.0.0"

# Trust Score Constants
MIN_TRUST_SCORE = 0
MAX_TRUST_SCORE = 100
INITIAL_TRUST_SCORE = 50

# Verification Levels
VERIFICATION_BASIC = 1      # Email + Phone
VERIFICATION_INTERMEDIATE = 2  # Government ID
VERIFICATION_ADVANCED = 3   # Biometric + Financial

# Organization Status
ORG_STATUS_PENDING = 0
ORG_STATUS_ACTIVE = 1
ORG_STATUS_SUSPENDED = 2
ORG_STATUS_DEACTIVATED = 3

# Certificate Status
CERT_STATUS_ACTIVE = 1
CERT_STATUS_REVOKED = 2
CERT_STATUS_EXPIRED = 3

# Badge Types
BADGE_TYPE_SKILL = 1
BADGE_TYPE_ACHIEVEMENT = 2
BADGE_TYPE_COMMUNITY = 3
BADGE_TYPE_PROFESSIONAL = 4
BADGE_TYPE_SOCIAL_IMPACT = 5

# Governance Proposal Types
PROPOSAL_TYPE_TECHNICAL = 1
PROPOSAL_TYPE_POLICY = 2
PROPOSAL_TYPE_DISPUTE = 3
PROPOSAL_TYPE_INTEGRATION = 4

# Proposal Status
PROPOSAL_STATUS_DRAFT = 0
PROPOSAL_STATUS_ACTIVE = 1
PROPOSAL_STATUS_PASSED = 2
PROPOSAL_STATUS_REJECTED = 3
PROPOSAL_STATUS_EXECUTED = 4

# Dispute Types
DISPUTE_TYPE_CERTIFICATE = 1
DISPUTE_TYPE_ORGANIZATION = 2
DISPUTE_TYPE_USER = 3
DISPUTE_TYPE_GOVERNANCE = 4

# Dispute Status
DISPUTE_STATUS_FILED = 1
DISPUTE_STATUS_JURY_SELECTION = 2
DISPUTE_STATUS_EVIDENCE = 3
DISPUTE_STATUS_DELIBERATION = 4
DISPUTE_STATUS_RESOLVED = 5
DISPUTE_STATUS_APPEALED = 6

# Economic Parameters
MIN_STAKE_AMOUNT = 1000000  # 1 ALGO in microAlgos
DISPUTE_BOND_AMOUNT = 5000000  # 5 ALGO in microAlgos
JURY_REWARD_AMOUNT = 100000  # 0.1 ALGO in microAlgos

# Time Constants (in seconds)
PROPOSAL_VOTING_PERIOD = 604800  # 7 days
DISPUTE_EVIDENCE_PERIOD = 259200  # 3 days
DISPUTE_DELIBERATION_PERIOD = 172800  # 2 days
RECOVERY_DELAY_PERIOD = 86400  # 24 hours

# Access Control Roles
ROLE_ADMIN = 1
ROLE_MODERATOR = 2
ROLE_VERIFIER = 3
ROLE_JUROR = 4

# Maximum Limits
MAX_CERTIFICATES_PER_USER = 1000
MAX_BADGES_PER_USER = 500
MAX_GUARDIANS_PER_WALLET = 10
MAX_JURY_SIZE = 7
MAX_PROPOSAL_DESCRIPTION_LENGTH = 1000

# Accreditation Types
ACCREDITATION_NATIONAL = 1
ACCREDITATION_REGIONAL = 2
ACCREDITATION_INTERNATIONAL = 3
ACCREDITATION_PROFESSIONAL = 4
ACCREDITATION_GOVERNMENT = 5
ACCREDITATION_INTERNAL = 6